### ISSUE TITLE
Lower the required version to 1.73.0

### ISSUE THREAD

**Issue by albert-ying** [docwilco/change-stepper#1]
Hi, I'm wondering if it possible to lower the required vscode version. Currently it require 1.74. However, many people choose to stay in 1.73 due to this issue https://github.com/iocave/customize-ui/issues/156

I tested myself, and the extension works for 1.73. It would be great if you could lower the required version.

**Comment by docwilco** [comment]
Updated, should roll out to Marketplace in a few minutes.

Thanks for the heads up!
